### ISSUE TITLE
Or in param types not displayed correctly

### ISSUE THREAD

**Issue by ambischof** [jsdoc2md/dmd-bitbucket#2]
In the bitbucket view: 

expected: 
``string|function``
actual 
``string &#124; function``

**Comment by 75lb** [comment]
confirmed, will release a patch this evening

**Comment by 75lb** [comment]
patched and released in 0.1.4

**Comment by ambischof** [comment]
Awesome, thanks for the quick action!

**Comment by 75lb** [comment]
you're welcome, let me know what other issues you find

**Comment by ambischof** [comment]
This doesn't actually work, It just creates another table column (since | is the column separator)

You'll likely need to use some other type of escaping for it.

**Comment by ambischof** [comment]
According to http://stackoverflow.com/questions/28436671/how-do-you-escape-pipe-character-in-bitbucket-markdown you can alternatively use unicode characters like the pipe since there doesn't seem to be a way to escape it.

**Comment by 75lb** [comment]
ok, i am now using the unicode pipe as suggested.. fixed in v0.1.5 - please update and try again.. cheers!
