### ISSUE TITLE
Class and subclass index format issues. (Nested bullets not working)

### ISSUE THREAD

**Issue by ambischof** [jsdoc2md/dmd-bitbucket#3]
The main issue is that nested lists after the second level don't render correctly. This shows itself especially in a class's index, especially when there are subclasses that have their own members.

When looking at the index of a class that has inner/static classes, the subclasses and subclasses' members are listed on what appears to be the same level, although in the source, they seem to be properly indented.

**Comment by 75lb** [comment]
fixed and released in 0.1.6, thanks for the report

**Comment by ambischof** [comment]
You're welcome, and thanks!
