### ISSUE TITLE
Horizontal rule not displaying correctly

### ISSUE THREAD

**Issue by ambischof** [jsdoc2md/dmd-bitbucket#4]
With the separator=true param, it just displays as a single dash (same as in source md file)
[This article](https://bitbucket.org/tutorials/markdowndemo/overview#markdown-header-horizontal-rules) shows how to create horizontal rules.

**Comment by 75lb** [comment]
ok.. yes, the single dash `-` is for Github (it produces a thinner hr than the default `* * *`)

**Comment by 75lb** [comment]
fixed and released in 0.1.7, thanks

**Comment by ambischof** [comment]
Thanks!

**Comment by 75lb** [comment]
oops, made a mistake and the separators were displayed even if you didn't set `--separators`.. this is fixed in 0.1.8
