### ISSUE TITLE
Markdown in tags without using --no-gfm

### ISSUE THREAD

**Issue by ambischof** [jsdoc2md/dmd-bitbucket#5]
See issue https://github.com/jsdoc2md/jsdoc-to-markdown/issues/71

The --no-gfm fix works fine outside of bitbucket, but in bitbucket, it breaks things like tables.

Is there any workaround that will work for bitbucket?

**Comment by 75lb** [comment]
ugh, bitbucket [does not support html tags like table](https://bitbucket.org/tutorials/markdowndemo).

the `--no-gfm` is a workaround to get markdown working inside markdown tables.. this particular workaround does not work on Bitbucket.. i don't think an alternative workaround exists.. could you play around and see if you can get your desired result using plain handwritten markdown? If you find a way, let me know the solution and i'll add it to the tool.

**Comment by 75lb** [comment]
the other way is to move away from using tables in your docs.. e.g. with `--param-list-format list`
